class insuranceElements{
    //Vehicle Tab
   MakeField = "#make"
   ModelField = "#model"
   CylinderField = "#cylindercapacity"
   EngineField = "#engineperformance"
   DateManufactureField = "#dateofmanufacture"
   NumberSeatsField = "#numberofseats"
   RightHandSection = ":nth-child(7) > .group"
   NumberSeatsMotor = "#numberofseatsmotorcycle"
   FuelTypeField = "#fuel"
   PayloadField = "#payload"
   TotalWeight = "#totalweight"
   ListPrice = "#listprice"
   LicensePlateField = "#licenseplatenumber"
   AnnualMileageField = "#annualmileage"
   NextButtonVehicle = "#nextenterinsurantdata"
   //Insurance Tab
   FirstNameField = "#firstname"
   LastNameField = "#lastname"
   DateOfBirthField = "#birthdate"
   GenderSection = ":nth-child(4) > .group"
   StreetAdress = "#streetaddress"
   ZipCodeField = "#zipcode"
   CountrySection = "#country"
   CityField = "#city"
   OccupationField = "#occupation"
   HobbiesSection = ":nth-child(2) > .idealforms-field-checkbox > .group"
   WebsiteField = "#website"
   NextButtonInsurance = "#nextenterproductdata"
   //Product tab
   StartDateField = "#startdate"
   InsuranceSumField = "#insurancesum"
   MeritRatingField = "#meritrating"
   DamageInsuranceField = "#damageinsurance"
   OptionalSection = ":nth-child(3) > .idealforms-field-checkbox > .group"
   CourtesyCarField = "#courtesycar"
   NextButtonProduct = "#nextselectpriceoption"
    //Select Price tab
    PriceOption = ":nth-child(3) > .ideal-radio"
    NextButtonPriceOption = "#nextsendquote"
    //Quote Tab
    EmailField = "#email"
    PhoneField = "#phone"
    UsernameField = "#username"
    PasswordField = "#password"
    ConfirmPasswordField = "#confirmpassword"
    SuccessMessage = ".sweet-alert"
}
export default insuranceElements 